### ISSUE TITLE
Feature: Save movie to list functionality

### ISSUE THREAD

**Issue by cgefx** [chingu-voyages/v21-geckos-team-03#21]

**Comment by marshallhelenm** [comment]
Createed a branch for this 7/21, dropdown and save button on movie card are in the works

**Comment by cgefx** [comment]
saw [this](https://chakra-ui.com/menu) in the chakra library today.   check the "menu group" option  (in pink about half way down)  - could be a good fit for this...

https://chakra-ui.com/menu

**Comment by marshallhelenm** [comment]
Sweet! That looks perfect for what I'm trying to implement. I'll work on getting that plugged in this morning.

**Comment by cgefx** [comment]
just had a thought on this that i ran into before...

as we are tweaking the movie object thats being added, theres sure to be old versions  of list documents in the db.  I can't recall 100%, but i think it crashes the app when trying to get snapshots of inconsistent documents from the same collection.  so feel free to delete any data directly in firebase if you need to ( even users)

**Comment by marshallhelenm** [comment]
Working on this I created a custom hook for fetching lists. As is in my last push I am calling that in every movie card so that I can generate the lists in the little "save to list" dropdown, but I realize now it would be a lot less processing power used if we only call that once at the page level and pass it down into the movie cards. I'll make that adjustment in the morning.
