### ISSUE TITLE
enhancement: add green check mark to lists in dropdown that the movie is already on/ that you have successfully added it to

### ISSUE THREAD

**Issue by marshallhelenm** [chingu-voyages/v21-geckos-team-03#65]

**Comment by marshallhelenm** [comment]
Checkmark appears when you save a movie, but does not load automatically upon loading the page.
To make that happen, we would need to make a db call for each list's movie collection. That would need to happen either for every moviecard, or at least in every place we load movie cards.
This doesn't seem worth it to me. @cgefx @Rayhan1998 What do you guys think? I think it's ok as is, as only a confirmation of your action.

**Comment by cgefx** [comment]
definitely ok as is!  but i'll chime in for any potential future enhancement 

I think there may be two ideas here and were kinda straddling the middle

1.) to provide feedback to confirm to the user that the movie has been added to a list. 

2.) to provide visual communication that a movie is already on a list.

since #1's outcome is the db layer, the message should probably come from there.  in that way a red check could be rendered instead, in the event of a network failure bad request, or something.

#2 is more like UI state coming from the backend that needs live comparison to API data. hmmm.. maybe a firebase observer that would always be listening and comparing? might look like the save movie query but with onsnapshot and the onList ternary logic 🤷🏻‍♂️

Or....Tweaking the click logic on the dropdown so it stays around long enough to see the check render is a quick hack that may improve the UX a bit.

**Comment by marshallhelenm** [comment]
I think you're right about that. Considerations for post MVP, I suppose. For now I'll make the menu stick around on select and make my pull request.
